### ISSUE TITLE
$data parameter required

### ISSUE THREAD

**Issue by iantasker** [ZiNETHQ/spark-invite#1]
When sending an invite the only think we know from the invitation are the requester, the requester's team and the invitee. 

When sending an invitation email we require additional data in the email like product, version etc. 

The easiest way to do this is via an additional data parameter which can be stored as a json object in additional field that will need to be added to the invitation table.

**Comment by drjonnicholson** [comment]
Added and pushed

**Comment by drjonnicholson** [comment]
@iantasker, let me know when you're happy with this in data exchange so I can close the issue.

**Comment by iantasker** [comment]
@drjonnicholson i have gone through this and it looks good.
