### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by nerdalertdk** [ZiNETHQ/spark-invite#3]
Hi

I get this error when trying to install it on a fresh laravel 5.45 and Spark 3.0.5

```
 composer require zinethq/spark-invite

  [InvalidArgumentException]
  Could not find package zinethq/spark-invite at any version for your minimum-stability (stable). Check the package s
  pelling or your minimum-stability
```

**Comment by drjonnicholson** [comment]
Hi @nerdalertdk, thanks for the feedback. Have tweaked the constraint on laravel version so it should now install in 5.4. Note that we've not tested in 5.4 and there may be other issues we're not aware of. Please keep us posted of your experience.
