### ISSUE TITLE
Invitation::class methods query a 'status' column that no longer exists

### ISSUE THREAD

**Issue by pryley** [ZiNETHQ/spark-invite#5]
Migration changes were introduced in c3de78f0d460a02b05435bf0742a6cda10d6af91 which broke the Invitation model methods.

Using `php artisan tinker`:
```php
>>> Invitation::getByInvitee( User::whereEmail( 'test@mail.com' )->first(), 'pending' );
```

## Expected Behavior
```php
=> Illuminate\Database\Eloquent\Collection { ... }
```

## Current Behavior
```log
Illuminate\Database\QueryException with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'where clause' (SQL: select * from `user_invitations` where `invitee_id` = 27 and `status` = pending order by `created_at` desc)'
```

## Possible Solution
It seems that the correct way to do this is as follows:
```php
$invitation = Invitation::getByInvitee(
    User::whereEmail( 'test@mail.com' )->first()
)->first();

if( $invitation->isPending() ) {
    // do something
}
```
Possible solution is to remove the deprecated method `$status` arguments.

## Your Environment
- Laravel Spark v4.0.9
- zinethq/spark-invite@dev-master

**Comment by drjonnicholson** [comment]
Hi there, thanks for this and #4. I've been on paternity and am playing catchup, but am now back and am looking into these. I've applied initial fixes to both issues, please let me know how you get on and if they solve the errors.

**Comment by drjonnicholson** [comment]
Assuming all ok at the moment on this, can always re-open if need be
